// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6A5Z62Fk7yJVJ_3-Bq4qYkTDId7FzR7Q',
    appId: '1:883088681674:web:68cbcfb9d6a9891d72e233',
    messagingSenderId: '883088681674',
    projectId: 'habitur-740df',
    authDomain: 'habitur-740df.firebaseapp.com',
    storageBucket: 'habitur-740df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFU2Uz4TPCVZLGmKOpnqHw2HKEkj8Aqs',
    appId: '1:883088681674:android:cd755fab805e474172e233',
    messagingSenderId: '883088681674',
    projectId: 'habitur-740df',
    storageBucket: 'habitur-740df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmd1EywY3IUn_d-hRY1IrMRZ07rcFNSxg',
    appId: '1:883088681674:ios:2c89e4528c81972772e233',
    messagingSenderId: '883088681674',
    projectId: 'habitur-740df',
    storageBucket: 'habitur-740df.appspot.com',
    iosClientId: '883088681674-g6pteodcri7808sennrd0l9h6j3e352i.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmd1EywY3IUn_d-hRY1IrMRZ07rcFNSxg',
    appId: '1:883088681674:ios:2c89e4528c81972772e233',
    messagingSenderId: '883088681674',
    projectId: 'habitur-740df',
    storageBucket: 'habitur-740df.appspot.com',
    iosClientId: '883088681674-g6pteodcri7808sennrd0l9h6j3e352i.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitur',
  );
}
