// Mocks generated by Mockito 5.4.4 from annotations
// in habitur/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:flutter/material.dart' as _i4;
import 'package:habitur/enums/activity_type.dart' as _i19;
import 'package:habitur/enums/reaction_type.dart' as _i20;
import 'package:habitur/models/activity_event.dart' as _i18;
import 'package:habitur/models/friend_request.dart' as _i8;
import 'package:habitur/models/habit.dart' as _i14;
import 'package:habitur/models/habit_interface.dart' as _i9;
import 'package:habitur/models/shared_habit.dart' as _i13;
import 'package:habitur/models/stat_point.dart' as _i16;
import 'package:habitur/models/user.dart' as _i10;
import 'package:habitur/services/activity_service.dart' as _i17;
import 'package:habitur/services/friends_service.dart' as _i7;
import 'package:habitur/services/habit_service.dart' as _i11;
import 'package:habitur/services/shared_habits_service.dart' as _i12;
import 'package:habitur/services/user_service.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:stacked_services/stacked_services.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i2.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i4.GlobalKey<_i4.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i4.GlobalKey<_i4.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i2.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<T?>? navigateWithTransition<T>(
    _i4.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i4.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i2.Transition? transitionClass,
    _i2.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  _i5.Future<T?>? replaceWithTransition<T>(
    _i4.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i4.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i2.Transition? transitionClass,
    _i2.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i4.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i4.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  _i5.Future<T?>? navigateToView<T>(
    _i4.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i4.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i2.Transition? transition,
    _i2.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  _i5.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i4.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  _i5.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  _i5.Future<T?>? clearStackAndShowView<T>(
    _i4.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  _i5.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  _i5.Future<T?>? clearTillFirstAndShowView<T>(
    _i4.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);

  @override
  _i5.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i4.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i5.Future<T?>?);
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i2.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i2.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i4.Widget Function(
      _i4.BuildContext,
      _i2.DialogRequest<dynamic>,
      dynamic Function(_i2.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i6.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i6.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i4.RouteSettings? routeSettings,
    _i4.GlobalKey<_i4.NavigatorState>? navigatorKey,
    _i2.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i5.Future<_i2.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i5.Future<_i2.DialogResponse<dynamic>?>.value(),
      ) as _i5.Future<_i2.DialogResponse<dynamic>?>);

  @override
  _i5.Future<_i2.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i6.Color? barrierColor = const _i6.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    _i4.RouteSettings? routeSettings,
    _i4.GlobalKey<_i4.NavigatorState>? navigatorKey,
    _i4.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i5.Future<_i2.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.DialogResponse<T>?>.value(),
      ) as _i5.Future<_i2.DialogResponse<T>?>);

  @override
  _i5.Future<_i2.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i6.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i6.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i4.RouteSettings? routeSettings,
    _i2.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i5.Future<_i2.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i5.Future<_i2.DialogResponse<dynamic>?>.value(),
      ) as _i5.Future<_i2.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i2.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FriendsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsService extends _i1.Mock implements _i7.FriendsService {
  @override
  _i5.Stream<List<String>> get friendsStream => (super.noSuchMethod(
        Invocation.getter(#friendsStream),
        returnValue: _i5.Stream<List<String>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<String>>.empty(),
      ) as _i5.Stream<List<String>>);

  @override
  _i5.Stream<List<_i8.FriendRequest>> get receivedRequestsStream =>
      (super.noSuchMethod(
        Invocation.getter(#receivedRequestsStream),
        returnValue: _i5.Stream<List<_i8.FriendRequest>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<_i8.FriendRequest>>.empty(),
      ) as _i5.Stream<List<_i8.FriendRequest>>);

  @override
  _i5.Stream<List<_i8.FriendRequest>> get sentRequestsStream =>
      (super.noSuchMethod(
        Invocation.getter(#sentRequestsStream),
        returnValue: _i5.Stream<List<_i8.FriendRequest>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<_i8.FriendRequest>>.empty(),
      ) as _i5.Stream<List<_i8.FriendRequest>>);

  @override
  _i5.Future<bool> isFriend(
    String? userId, {
    String? otherUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFriend,
          [userId],
          {#otherUserId: otherUserId},
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> sendFriendRequest(String? recipientUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [recipientUid],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendFriendRequestByUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequestByUsername,
          [username],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> acceptFriendRequest(_i8.FriendRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [request],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> declineFriendRequest(_i8.FriendRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #declineFriendRequest,
          [request],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelFriendRequest(_i8.FriendRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelFriendRequest,
          [request],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.HabitInterface>> getFriendVisibleHabits(
          String? friendUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriendVisibleHabits,
          [friendUid],
        ),
        returnValue:
            _i5.Future<List<_i9.HabitInterface>>.value(<_i9.HabitInterface>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i9.HabitInterface>>.value(<_i9.HabitInterface>[]),
      ) as _i5.Future<List<_i9.HabitInterface>>);

  @override
  _i5.Future<List<_i10.UserModel>> getFriends() => (super.noSuchMethod(
        Invocation.method(
          #getFriends,
          [],
        ),
        returnValue: _i5.Future<List<_i10.UserModel>>.value(<_i10.UserModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i10.UserModel>>.value(<_i10.UserModel>[]),
      ) as _i5.Future<List<_i10.UserModel>>);

  @override
  void enableFriendsService() => super.noSuchMethod(
        Invocation.method(
          #enableFriendsService,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disableFriendsService() => super.noSuchMethod(
        Invocation.method(
          #disableFriendsService,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HabitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitService extends _i1.Mock implements _i11.HabitService {
  @override
  List<_i9.HabitInterface> get habits => (super.noSuchMethod(
        Invocation.getter(#habits),
        returnValue: <_i9.HabitInterface>[],
        returnValueForMissingStub: <_i9.HabitInterface>[],
      ) as List<_i9.HabitInterface>);

  @override
  _i5.Stream<List<_i9.HabitInterface>> get habitsStream => (super.noSuchMethod(
        Invocation.getter(#habitsStream),
        returnValue: _i5.Stream<List<_i9.HabitInterface>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<_i9.HabitInterface>>.empty(),
      ) as _i5.Stream<List<_i9.HabitInterface>>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.Future<void> loadHabits() => (super.noSuchMethod(
        Invocation.method(
          #loadHabits,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadFromRemote() => (super.noSuchMethod(
        Invocation.method(
          #loadFromRemote,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteHabit(String? habitId) => (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [habitId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementHabit(
    String? habitId,
    double? difficultyRating, {
    int? amount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementHabit,
          [
            habitId,
            difficultyRating,
          ],
          {#amount: amount},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> decrementHabit(
    String? habitId, {
    int? amount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrementHabit,
          [habitId],
          {#amount: amount},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.HabitInterface>> getTodaysDueHabits() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodaysDueHabits,
          [],
        ),
        returnValue:
            _i5.Future<List<_i9.HabitInterface>>.value(<_i9.HabitInterface>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i9.HabitInterface>>.value(<_i9.HabitInterface>[]),
      ) as _i5.Future<List<_i9.HabitInterface>>);

  @override
  bool isDue(_i9.HabitInterface? habit) => (super.noSuchMethod(
        Invocation.method(
          #isDue,
          [habit],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int getWeekOfYear(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getWeekOfYear,
          [date],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.Future<void> resetDailyHabits() => (super.noSuchMethod(
        Invocation.method(
          #resetDailyHabits,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetWeeklyHabits() => (super.noSuchMethod(
        Invocation.method(
          #resetWeeklyHabits,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetMonthlyHabits() => (super.noSuchMethod(
        Invocation.method(
          #resetMonthlyHabits,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetHabits() => (super.noSuchMethod(
        Invocation.method(
          #resetHabits,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> calculateHabitStats() => (super.noSuchMethod(
        Invocation.method(
          #calculateHabitStats,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<DateTime> getDaysCompleted(_i9.HabitInterface? habit) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDaysCompleted,
          [habit],
        ),
        returnValue: <DateTime>[],
        returnValueForMissingStub: <DateTime>[],
      ) as List<DateTime>);

  @override
  _i5.Future<void> saveHabits(List<_i9.HabitInterface>? habits) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHabits,
          [habits],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.HabitInterface>> getUserHabits({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserHabits,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i5.Future<List<_i9.HabitInterface>>.value(<_i9.HabitInterface>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i9.HabitInterface>>.value(<_i9.HabitInterface>[]),
      ) as _i5.Future<List<_i9.HabitInterface>>);

  @override
  _i5.Future<List<_i9.HabitInterface>> getVisibleHabits({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisibleHabits,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i5.Future<List<_i9.HabitInterface>>.value(<_i9.HabitInterface>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i9.HabitInterface>>.value(<_i9.HabitInterface>[]),
      ) as _i5.Future<List<_i9.HabitInterface>>);

  @override
  _i5.Future<void> addHabit(_i9.HabitInterface? habit) => (super.noSuchMethod(
        Invocation.method(
          #addHabit,
          [habit],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateHabit(_i9.HabitInterface? habit) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHabit,
          [habit],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i9.HabitInterface?> getHabit(String? habitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHabit,
          [habitId],
        ),
        returnValue: _i5.Future<_i9.HabitInterface?>.value(),
        returnValueForMissingStub: _i5.Future<_i9.HabitInterface?>.value(),
      ) as _i5.Future<_i9.HabitInterface?>);

  @override
  double calculateConsistencyFactor(_i9.HabitInterface? habit) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateConsistencyFactor,
          [habit],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SharedHabitsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedHabitsService extends _i1.Mock
    implements _i12.SharedHabitsService {
  @override
  List<_i13.SharedHabit> get sharedHabits => (super.noSuchMethod(
        Invocation.getter(#sharedHabits),
        returnValue: <_i13.SharedHabit>[],
        returnValueForMissingStub: <_i13.SharedHabit>[],
      ) as List<_i13.SharedHabit>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.Future<List<_i13.SharedHabit>> getSharedHabits() => (super.noSuchMethod(
        Invocation.method(
          #getSharedHabits,
          [],
        ),
        returnValue:
            _i5.Future<List<_i13.SharedHabit>>.value(<_i13.SharedHabit>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i13.SharedHabit>>.value(<_i13.SharedHabit>[]),
      ) as _i5.Future<List<_i13.SharedHabit>>);

  @override
  _i5.Future<void> createSharedHabit(_i13.SharedHabit? sharedHabit) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSharedHabit,
          [sharedHabit],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSharedHabit(_i13.SharedHabit? sharedHabit) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSharedHabit,
          [sharedHabit],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSharedHabit(String? habitId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSharedHabit,
          [habitId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementHabit(
    String? habitId,
    double? difficultyRating, {
    int? amount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementHabit,
          [
            habitId,
            difficultyRating,
          ],
          {#amount: amount},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> decrementHabit(
    String? habitId, {
    int? amount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrementHabit,
          [habitId],
          {#amount: amount},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateParticipantProgress(
    _i13.SharedHabit? sharedHabit,
    String? userId,
    _i14.Habit? participantHabitData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateParticipantProgress,
          [
            sharedHabit,
            userId,
            participantHabitData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i13.SharedHabit?> getSharedHabitById(int? habitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSharedHabitById,
          [habitId],
        ),
        returnValue: _i5.Future<_i13.SharedHabit?>.value(),
        returnValueForMissingStub: _i5.Future<_i13.SharedHabit?>.value(),
      ) as _i5.Future<_i13.SharedHabit?>);

  @override
  _i5.Future<_i13.SharedHabit?> convertHabitToSharedHabit(
    _i14.Habit? habit,
    List<_i10.UserModel>? participants,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertHabitToSharedHabit,
          [
            habit,
            participants,
          ],
        ),
        returnValue: _i5.Future<_i13.SharedHabit?>.value(),
        returnValueForMissingStub: _i5.Future<_i13.SharedHabit?>.value(),
      ) as _i5.Future<_i13.SharedHabit?>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i15.UserService {
  @override
  _i5.Stream<_i10.UserModel?> get userStream => (super.noSuchMethod(
        Invocation.getter(#userStream),
        returnValue: _i5.Stream<_i10.UserModel?>.empty(),
        returnValueForMissingStub: _i5.Stream<_i10.UserModel?>.empty(),
      ) as _i5.Stream<_i10.UserModel?>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool isSameDay(
    DateTime? date1,
    DateTime? date2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isSameDay,
          [
            date1,
            date2,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> updateCompletions(
    _i10.UserModel? user, {
    double? amount = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCompletions,
          [user],
          {#amount: amount},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> undoCompletion(
    _i10.UserModel? user, {
    double? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #undoCompletion,
          [user],
          {#amount: amount},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateConfidenceLevel(
    _i10.UserModel? user,
    double? newConfidenceLevel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfidenceLevel,
          [
            user,
            newConfidenceLevel,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i16.StatPoint> getStatsForDateRange(
    _i10.UserModel? user,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatsForDateRange,
          [
            user,
            startDate,
            endDate,
          ],
        ),
        returnValue: <_i16.StatPoint>[],
        returnValueForMissingStub: <_i16.StatPoint>[],
      ) as List<_i16.StatPoint>);

  @override
  List<_i16.StatPoint> getStats(_i10.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [user],
        ),
        returnValue: <_i16.StatPoint>[],
        returnValueForMissingStub: <_i16.StatPoint>[],
      ) as List<_i16.StatPoint>);

  @override
  _i5.Future<void> unlogHabitCompletion() => (super.noSuchMethod(
        Invocation.method(
          #unlogHabitCompletion,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> recordAverageConfidenceLevel(List<_i14.Habit>? habits) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordAverageConfidenceLevel,
          [habits],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fillInMissingDays() => (super.noSuchMethod(
        Invocation.method(
          #fillInMissingDays,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sortStats() => (super.noSuchMethod(
        Invocation.method(
          #sortStats,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateStats(List<_i14.Habit>? habits) => (super.noSuchMethod(
        Invocation.method(
          #updateStats,
          [habits],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i10.UserModel?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i10.UserModel?>.value(),
        returnValueForMissingStub: _i5.Future<_i10.UserModel?>.value(),
      ) as _i5.Future<_i10.UserModel?>);

  @override
  _i5.Future<_i10.UserModel?> getUserById(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i5.Future<_i10.UserModel?>.value(),
        returnValueForMissingStub: _i5.Future<_i10.UserModel?>.value(),
      ) as _i5.Future<_i10.UserModel?>);

  @override
  _i5.Future<void> createUser(_i10.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUser(_i10.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #loadUser,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadFromRemote() => (super.noSuchMethod(
        Invocation.method(
          #loadFromRemote,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadFromLocal() => (super.noSuchMethod(
        Invocation.method(
          #loadFromLocal,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ActivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityService extends _i1.Mock implements _i17.ActivityService {
  @override
  List<_i18.ActivityEvent> get activities => (super.noSuchMethod(
        Invocation.getter(#activities),
        returnValue: <_i18.ActivityEvent>[],
        returnValueForMissingStub: <_i18.ActivityEvent>[],
      ) as List<_i18.ActivityEvent>);

  @override
  bool get hasMore => (super.noSuchMethod(
        Invocation.getter(#hasMore),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isEnabled => (super.noSuchMethod(
        Invocation.getter(#isEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.Future<_i18.ActivityEvent?> getActivity(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivity,
          [activityId],
        ),
        returnValue: _i5.Future<_i18.ActivityEvent?>.value(),
        returnValueForMissingStub: _i5.Future<_i18.ActivityEvent?>.value(),
      ) as _i5.Future<_i18.ActivityEvent?>);

  @override
  _i5.Future<_i5.Stream<List<_i18.ActivityEvent>>> getActivitiesStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivitiesStream,
          [],
        ),
        returnValue: _i5.Future<_i5.Stream<List<_i18.ActivityEvent>>>.value(
            _i5.Stream<List<_i18.ActivityEvent>>.empty()),
        returnValueForMissingStub:
            _i5.Future<_i5.Stream<List<_i18.ActivityEvent>>>.value(
                _i5.Stream<List<_i18.ActivityEvent>>.empty()),
      ) as _i5.Future<_i5.Stream<List<_i18.ActivityEvent>>>);

  @override
  _i5.Future<void> loadInitialActivities() => (super.noSuchMethod(
        Invocation.method(
          #loadInitialActivities,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadMoreActivities() => (super.noSuchMethod(
        Invocation.method(
          #loadMoreActivities,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createActivity(_i18.ActivityEvent? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #createActivity,
          [activity],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createActivityForEvent(
    String? userId,
    String? username,
    _i19.ActivityType? type,
    String? habitId,
    String? habitTitle, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createActivityForEvent,
          [
            userId,
            username,
            type,
            habitId,
            habitTitle,
          ],
          {#metadata: metadata},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> likeActivity(String? activityId) => (super.noSuchMethod(
        Invocation.method(
          #likeActivity,
          [activityId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unlikeActivity(String? activityId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeActivity,
          [activityId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteActivity(String? activityId) => (super.noSuchMethod(
        Invocation.method(
          #deleteActivity,
          [activityId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleReaction(
    String? activityId,
    _i20.ReactionType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleReaction,
          [
            activityId,
            type,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addComment(
    String? activityId,
    _i18.Comment? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [
            activityId,
            comment,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void enableActivityService() => super.noSuchMethod(
        Invocation.method(
          #enableActivityService,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disableActivityService() => super.noSuchMethod(
        Invocation.method(
          #disableActivityService,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
